#!/bin/sh

## hyphop ##

#= online launcher

GAME=15sh
SRC=https://raw.githubusercontent.com/hyphop/$GAME/master/$GAME
DST=/tmp/$GAME

SHELL=$(which bash)
[ "$SHELL" ] || SHELL=$(which sh)

GET=$(which curl)
[ "$GET" ] || GET=$(which wget)
OPT=

case $GET in
    *wget)
    OPT="-O-"
    ;;
    *curl)
    OPT="-jkfL"
    ;;
esac

i=0
PID=$$
PPID=$$
IN=
AGAIN=1
while [ "$AGAIN" ] ; do
for PPID in $(cat /proc/$PPID/stat); do
#    echo $PPID
    [ $i = 3 ] && {
    i=0
    IN=$(readlink /proc/$PPID/fd/0)
    case $IN in
	pipe*)
	break
	;;
	pts*)
	;;
	*)
	;;
    esac
    AGAIN=
    break
    }
    i=$((i+1))
done
done

#ls -l1 /proc/self/fd/0

echo "[i] ONLINE LAUNCHER => $GAME">&2
echo "[i] IN: $IN PID: $PID PPID: $PPID | SHELL: $SHELL + GET: $GET $OPT SRC: $SRC=>$DST">&2

$GET $OPT $SRC > $GAME && exec $SHELL $DST $@ <$IN

